openapi: 3.0.0
info:
  title: Sample API
  description: Optional multiline or single-line description.
  version: 1.0.0

servers:
  - url: http://localhost:2500/api/v1
    description: Localhost version of our app
  - url: https://localhost:2500/api/v1
    description: This is our dummy server testing

components:
  securitySchemes:
    BasicAuth:
      type: http
      scheme: basic
    BearerAuth:
      type: http
      scheme: bearer

